# Generated by Django 3.2.16 on 2022-12-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '普通会员'), (2, 'VIP'), (3, 'SVIP')], default=1, verbose_name='级别')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='TOKEN')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serializer_related.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo2Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serializer_related.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serializer_related.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(through='serializer_related.Userinfo2Roles', to='serializer_related.Role', verbose_name='角色'),
        ),
    ]
