# Generated by Django 3.2.16 on 2022-12-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '管理员'), (3, '超级管理员')], default=1, verbose_name='角色'),
        ),
    ]
